// This file is generated by Slice Machine. Update with care!

import BlogText from './BlogText';
import ContactForm from './ContactForm';
import Image from './Image';
import Link from './Link';
import PostLinkWithCustomTitle from './PostLinkWithCustomTitle';
import Quote from './Quote';
import RecentArticlesList from './RecentArticlesList';
import Subtitle from './Subtitle';
import Text from './Text';

export {
	BlogText,
	ContactForm,
	Image,
	Link,
	PostLinkWithCustomTitle,
	Quote,
	RecentArticlesList,
	Subtitle,
	Text,
};

export const components = {
	blog_text: BlogText,
	contact_form: ContactForm,
	image: Image,
	link: Link,
	post_link_with_custom_title: PostLinkWithCustomTitle,
	quote: Quote,
	recent_articles_list: RecentArticlesList,
	subtitle: Subtitle,
	text: Text,
};
